version: '3.8'

networks:
  pre-event-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: pre-event-mysql
    volumes:
      - ./data/db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d  # Thư mục chứa các script khởi tạo
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'  # Buộc tất cả kết nối sử dụng utf8mb4
    ]
    environment:
        MYSQL_ROOT_PASSWORD: root1234
        MYSQL_DATABASE: ticket
        MYSQL_PASSWORD: root1234
    ports:
      - "3306:3306"
    networks:
      - pre-event-network

  # Redis service
  redis:
    container_name: pre-event-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pre-event-network

  # prometheus
  prometheus:
    container_name: pre-event-prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - pre-event-network
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  # Grafana service
  grafana:
    container_name: pre-event-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    hostname: pre-event-grafana
    ports:
      - "3000:3000"
    networks:
      - pre-event-network
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data/grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin1234
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=allerting.notifier.slack:debug alleart manager :debug notifier:debug ngalert:debug

  #node exporters
  node-exporter:
    container_name: pre-event-node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - pre-event-network
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  # Redis exporter
  redis-exporter:
    container_name: pre-event-redis-exporter
    image: oliver006/redis_exporter:latest
    restart: unless-stopped
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - pre-event-network
    depends_on:
      - redis

  # MySQL exporter
  mysqld-exporter:
    container_name: pre-event-mysqld-exporter
    image: prom/mysqld-exporter:latest
    restart: unless-stopped
    ports:
      - "9104:9104"
    networks:
      - pre-event-network
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - DATA_SOURCE_NAME=root:root1234@(mysql:3306)/ticket
    command:
      - '--config.my-cnf=/etc/mysql/.my.cnf'
      - '--collect.engine_innodb_status'
      - '--collect.info_schema.processlist'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.query_response_time'
      - '--collect.perf_schema.file_events'
      - '--collect.perf_schema.eventsstatements'
      - '--collect.perf_schema.indexiowaits'
      - '--collect.global_status'
    volumes:
      - ./mysqld-exporter/.my.cnf:/etc/mysql/.my.cnf:ro
    depends_on:
      - mysql