input {
  tcp {
    port => 5000
    codec => json_lines
  }
  udp {
    port => 5000
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

filter {
  if [logger_name] {
    mutate {
      add_field => { "service" => "zzz.com" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "preticket-logs-%{+YYYY.MM.dd}"
  }
}
