@url_dev=http://localhost:8010

//signup
POST {{url_dev}}/v1/shop/signup
Content-Type: application/json
x-api-key: ece78252d991e1f6dcb6736c14d443fe27ee798589e85327d7ec42158e696c26

{
    "name": "Shop2",
    "email": "tgkhang22@clc.fitus",
    "password": "Demo@123"
}
